#!/usr/bin/env bash

function sendcommand
{
  # Flush any input
  read -u4 -t1
  printf "at+cgns$1\r" >&4
  read -u4 -t10 answer1
  read -u4 -t10 answer2
  read -u4 -t10 answer3
  read -u4 -t10 answer4
}

exec 4<>/dev/ttyS0
stty -F /dev/ttyS0 115200 cs8 -cstopb raw -echo

sendcommand "pwr=1"
echo "answer1"
xxd <<< "$answer1"
echo "answer2"
xxd <<< "$answer2"
echo "answer3"
xxd <<< "$answer3"
echo "answer4"
xxd <<< "$answer4"

exec 4>&-
