#!/usr/bin/env bash
# Script to be called by udev RUN
# This script assumes that the sim868 module NVRAM
# is configured to a fixed baud rate of 115200
# and not to echo commands.
# This can be done by conenecting a terminal emulator
# such as minicom to the serial port and issuing the following commands
# at&ipr=115200
# ate0
# at&w
# Note that the final command will not be echoed.

function flush_input
{
  # Flush any input
  while read -u4 -t0
  do
    read -u4
  done
}

function read_response
{
  sleep 1
  read -u4 -N2 -t10 response
}

function sendcommand
{
  # Flush any input
  flush_input
  while read -u4 -t0
  do
    read -u4
  done
  printf "at+cgns$1\r" >&4
  read_response
}

exec 4<>/dev/ttyS0
stty -F /dev/ttyS0 115200 cs8 -cstopb raw -echo

# Test if hat is powered
until [ "$response" = "OK" ]; do
  flush_input
  printf "at\r" >&4
  read_response
  if [ "$response" != "OK" ]; then
    gpioset -m time -s 3 0 4=0
  fi
done

sendcommand "pwr=1"
if [ "$response" != "OK" ]; then
  exit -1
fi

exec 4>&-
