#!/usr/bin/env bash
# Script to be called by udev RUN
# This script assumes that the sim868 module NVRAM
# is configured to a fixed baud rate of 115200
# and not to echo commands.
# This can be done by conenecting a terminal emulator
# such as minicom to the serial port and issuing the following commands
# at&ipr=115200
# ate0
# at&w
# Note that the final command will not be echoed.

function flush_input
{
  # Flush any input
  printf "Flushing input\n"
  while read -u4 -t0
  do
    printf "Discarding\n"
    read -u4 discard
    xxd <<< $discard
  done
  printf "Flushed\n"
}

function read_response
{
  printf "Read response %d\n" $1
  sleep 1
  read -u4 -t $1 response
  xxd <<< $response
}

function sendcommand
{
  printf "sendcommand - %s" 
  # Flush any input
  flush_input
  printf "at+cgns$1\r" >&4
}

exec 4<>/dev/ttyS0
stty -F /dev/ttyS0 115200 cs8 -cstopb raw -echo igncr

# Test if hat is powered
flush_input
printf "at\r" >&4
read_response 2
if [ "$response" != "OK" ]; then
  printf "Pulling down gpio4\n"
  gpioset -m time -s 3 0 4=0
  # Wait for RDY
  until [ "$response" = "RDY" ]; do
    read_response 1
    printf "Got response -%s-\n" $response
  done
fi

# Hat is powered
# Turn on gps
sendcommand "pwr=1"
until [ "$response" = "OK" ]; do
  read_response 1
done

# Turn on test mode
response=
sendcommand "tst=1"
until [ "$response" = "OK" ]; do
  read_response 1
done

printf "Success\n"

exec 4>&-
