#!/usr/bin/env bash

function flush_input
{
  # Flush any input
  while read -u4 -t0
  do
    read -u4
  done
}

function read_response
{
  sleep 1
  read -u4 -N2 -t10 response
}

function sendcommand
{
  # Flush any input
  flush_input
  while read -u4 -t0
  do
    read -u4
  done
  printf "at+cgns$1\r" >&4
  read_response
}

exec 4<>/dev/ttyS0
stty -F /dev/ttyS0 115200 cs8 -cstopb raw -echo

sendcommand "pwr=1"
echo $response

exec 4>&-
