#!/usr/bin/env bash


function flush_input
{
  # Flush any input
  printf "Flushing input\n"
  while read -u4 -t0
  do
    printf "Discarding\n"
    read -u4 discard
    xxd <<< $discard
  done
  printf "Flushed\n"
}

function read_response
{
  printf "Read response %d\n" $1
  read -u4 -t $1 response
  xxd <<< $response
}

function sendcommand
{
  printf "sendcommand - %s"
  # Flush any input
  flush_input
  printf "at+cgns$1\r" >&4
}

printf "Opening /dev/ttyS0\n"
exec 4<>/dev/ttyS0
stty -F /dev/ttyS0 115200 cs8 -cstopb raw -echo igncr

function flush_input
{
  # Flush any input
  printf "Flushing input\n"
  while read -u4 -t0
  do
    printf "Discarding\n"
    read -u4 discard
    xxd <<< $discard
  done
  printf "Flushed\n"
}

function read_response
{
  printf "Read response %d\n" $1
  read -u4 -t $1 response
  xxd <<< $response
}

function sendcommand
{
  printf "sendcommand - %s"
  # Flush any input
  flush_input
  printf "at+cgns$1\r" >&4
}

printf "Opening /dev/ttyS0\n"
exec 4<>/dev/ttyS0
stty -F /dev/ttyS0 115200 cs8 -cstopb raw -echo igncr

# Turn on gps
sendcommand "pwr=1"
until [ "$response" = "OK" ]; do
  read_response 1
done

# Turn on test mode
response=
sendcommand "tst=1"
until [ "$response" = "OK" ]; do
  read_response 1
done

printf "Success\n"

exec 4>&-
