#!/usr/bin/env python

from gps import *
import time
import gpxpy
import gpxpy.gpx
from datetime import datetime
import logging
from systemd.journal import JournalHandler

logging.basicConfig(format='%(asctime)s %(message)s')
log = logging.getLogger("gps-logger")
log.propagate = False
log.addHandler(JournalHandler())
log.setLevel(logging.INFO)

TIME_INTERVAL_SECONDS = 30.0
MAX_SEGMENT_TIME = 900.0
running = True

def saveCurrentSegment():
    gpx.reduce_points(None, 2.5)
    with open(datetime.now().strftime("%Y-%m-%dT%H:%M:%S.gpx"), "w") as f:
        f.write(gpx.to_xml())
    gpx_segment.points.clear()
    log.debug("Segment saved")

def getPositionData(gps):
    while True:
        try:
            nx = gpsd.next()
        except ConnectionError:
            log.debug("ConnectionError")
            continue
        log.debug("Class = %s", nx['class'])
        if nx['class'] == 'TPV':
            latitude = getattr(nx,'lat', "Unknown")
            longitude = getattr(nx,'lon', "Unknown")
            elevation = getattr(nx, 'altHAE', "Unknown")
            gpx_segment.points.append(gpxpy.gpx.GPXTrackPoint(latitude, longitude, elevation))
            # If the number of points saved multiplied by the time interval is greater
            # than the maximum segment size then save the current segment and reset it.
            log.debug("Current points %d", len(gpx_segment.points))
            if (len(gpx_segment.points) * TIME_INTERVAL_SECONDS) > MAX_SEGMENT_TIME:
                saveCurrentSegment()
            return
        else:
            continue

log.info("Gps logger started")
gpsd = gps(mode=WATCH_ENABLE|WATCH_NEWSTYLE)

gpx = gpxpy.gpx.GPX()
gpx_track = gpxpy.gpx.GPXTrack()
gpx.tracks.append(gpx_track)
gpx_segment = gpxpy.gpx.GPXTrackSegment()
gpx_track.segments.append(gpx_segment)

try:
    while running:
        log.debug("Tick")
        getPositionData(gpsd)
        log.debug("Tock");
        time.sleep(TIME_INTERVAL_SECONDS)

except (KeyboardInterrupt):
    log.info("Keyboard interrupt")
    running = False
    saveCurrentSegment()
    
log.info("Gps logger stopped")
